### ISSUE TITLE
How to get pretrained model?

### ISSUE THREAD

**Issue by hyeonjinXZ** [soloist97/densecap-pytorch#2]
Hello.

I'm glad I found your nice work! Thank you.
I am trying to download pre-trained model as outlined in [Readme](https://github.com/soloist97/densecap-pytorch#trained-model).

1. There are two pth.tar files when I access to the [OneDrive](https://onedrive.live.com/?cid=0830254425607863&id=830254425607863%2190251&authkey=!ANB0A8IJe_URA80). Which one is a pretrained model? And what is the difference between them?

2. When I downloaded them, there are no files in pth.tar files like below screenshot. Could you please check if that file is still available?
![image](https://user-images.githubusercontent.com/39545805/148660899-d05448a9-dfa2-43b3-b943-de6fb5432284.png)

**Comment by soloist97** [comment]
Hi,

1. The checkpoint file `train_all_val_all_bz_2_epoch_10_inject_init.pth.tar` is the pretrained checkpoint mentioned in README.  The `xxx_end.pth.tar` version was trained for exact 10 epochs, while the `xxx.pth.tar` version was chosen by best validate set performance within 10 epochs (i.e. early stopping).

2. I have checked the file is available. Try to use `torch.load(<path-of-checkpoint>)` to load the checkpoint file instead of extract it directly.  If you still cannot use it, feel free to post more information.

**Comment by hyeonjinXZ** [comment]
Thank you for your kind reply!

1. I will load `train_all_val_all_bz_2_epoch_10_inject_init.pth.tar` as the pretrained model. 
2. It works well with `torch.load`.
